# Done to increase the memory available to gradle.
# add-exports are needed for spotless to work on new Javas
org.gradle.jvmargs=-Xmx3G \
  --add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED
org.gradle.daemon=false

## Environment Properties
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,)
forge_version=47.1.3
forge_version_range=[47,)
loader_version_range=[47,)
fabric_loader_version=0.15.6
fabric_api_version=0.92.1+1.20.1

mapping_channel=parchment
mapping_version=2023.09.03


build_number=1
artifact_name = EventWrapper
## Mod Properties

mod_id=eventwrapper
mod_name=Event Wrapper
mod_license=MIT License
mod_version=1.0.1
mod_group_id=io.github.lounode.eventwrapper
mod_logo=assets/eventwrapper/textures/logo.png
mod_authors=Lounode
mod_description=A event wrapper for mod crossing forge and fabric

## Depends
jei_version=15.2.0.27
jei_version_range=[1.20.1-15.2.0.27,)
