plugins {
    id 'java'
    id 'java-library'
    id 'net.neoforged.moddev.legacyforge' version '2.0.78'
}

base.archivesName = mod_id + "-" + "forge"
version = "${minecraft_version}-${mod_version}"

if (System.getenv().RELEASE_MODE != "1") {
    version += '-SNAPSHOT'
}

repositories {
    maven {
        name = "Jared"
        url = "https://maven.blamejared.com/"
    }
    maven {
        name = "C4"
        url = "https://maven.theillusivec4.top/"
    }
    maven {
        name = "TerraformersMC"
        url = "https://maven.terraformersmc.com/" // for emi
    }
    maven {
        name = "Unascribed"
        url = "https://repo.unascribed.com" // for ears
        content {
            includeGroup "com.unascribed"
        }
    }
    maven { // CURSE
        name = "CurseMaven"
        url = "https://www.cursemaven.com/"
        content {
            includeGroup "curse.maven"
        }
    }
}

mixin{
    add sourceSets.main, "eventwrapper.refmap.json"

    config "eventwrapper_common.mixins.json"
    config "eventwrapper_forge.mixins.json"
}

legacyForge {
    version = minecraft_version + "-" + forge_version
    accessTransformers = [project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')]

    parchment {
        minecraftVersion = minecraft_version
        mappingsVersion = mapping_version
    }

    runs {
        client {
            client()
            systemProperty('forge.logging.console.level', 'debug')

            jvmArgument("-DdebugEvent=true")
            jvmArgument("-XX:+AllowEnhancedClassRedefinition")
        }

        server {
            server()
            systemProperty('forge.logging.console.level', 'debug')

            jvmArgument("-XX:+AllowEnhancedClassRedefinition")
        }

        configureEach {
            gameDirectory = file('../run/')
            systemProperty('fml.earlyprogresswindow', 'false')

            programArguments.addAll("--username", "Dev")
            programArguments.addAll("--uuid", "4f201c25-b473-4c2c-959a-dea681f79c23")
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
            sourceSet project(":common").sourceSets.main
        }
    }
}

dependencies {
    compileOnly project(":common")
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'

    modRuntimeOnly("mezz.jei:jei-${minecraft_version}-forge:${jei_version}")
}

sourceSets.main.java {
    exclude 'io/github/lounode/eventwrapper/fabric/**'
}

sourceSets.main.resources {
    srcDir 'src/generated/resources'
}

compileJava {
    source(project(":common").sourceSets.main.allSource)
    options.compilerArgs << "-Xlint:all,-classfile,-processing,-deprecation,-serial"
}

sourcesJar {
    from project(":common").sourceSets.main.allJava
}

processResources {
    from project(":common").sourceSets.main.resources
    inputs.property "version", project.version

    // Exclude datagenerator .cache directory
    exclude '.cache'
}

def generateModMetadataForge = tasks.register('generateModMetadataForge', ProcessResources) {
    var replaceProperties = [
            minecraft_version: minecraft_version, minecraft_version_range: minecraft_version_range,
            forge_version: forge_version, forge_version_range: forge_version_range,
            loader_version_range: loader_version_range,
            mod_id: mod_id, mod_name: mod_name, mod_license: mod_license, mod_version: mod_version,
            mod_authors: mod_authors, mod_description: mod_description, mod_logo: mod_logo,
            jei_version: jei_version, jei_version_range: jei_version_range,
    ]
    inputs.properties replaceProperties
    expand replaceProperties


    from "src/main/template"
    into "build/generated/sources/modMetaData"
}

sourceSets.main.resources.srcDir generateModMetadataForge
legacyForge.ideSyncTask generateModMetadataForge

jar {
    manifest {
        attributes([
                "Specification-Title": "${artifact_name}",
                "Specification-Vendor": "lounode",
                "Specification-Version": "1", // We are version 1 of ourselves
                "Implementation-Title": "${artifact_name}",
                "Implementation-Version": "${archiveVersion.get()}",
                "Implementation-Vendor" :"lounode",
                "MixinConfigs": "eventwrapper_common.mixins.json,eventwrapper_forge.mixins.json"
        ])
    }
    finalizedBy 'reobfJar'
}
/*
task apiJar(type: Jar, dependsOn: classes) {
    // Sources included because of MinecraftForge/ForgeGradle#369
    from project(":common").sourceSets.main.allJava
    from(sourceSets.main.allJava)
    from(sourceSets.main.output)

    include 'java/io/github/lounode/eventwrapper/api/**'

    archiveClassifier = 'api'
}
 */

publishing {
    publications {
        mavenJava(MavenPublication) {
            groupId = mod_group_id
            artifactId = base.archivesName.get()
            version = project.version
            artifact jar
            artifact sourcesJar
            //artifact apiJar
            pom.withXml {
                def node = asNode()
                if(node.dependencies.size() > 0)
                    node.remove(node.dependencies) // Remove deps, as they are all mappings-dependent and/or forge
            }
        }
    }

    repositories {
        if (System.getenv("GITHUB_ACTIONS") != null) {
            if (System.getenv().RELEASE_MODE != "1") {
                maven {
                    name = "lounode"
                    url = "https://maven.lounode.top/snapshots"
                    credentials {
                        username = System.getenv("MAVEN_USERNAME")
                        password = System.getenv("MAVEN_TOKEN")
                    }
                }
            } else {
                maven {
                    name = "lounode"
                    url = "https://maven.lounode.top/releases"
                    credentials {
                        username = System.getenv("MAVEN_USERNAME")
                        password = System.getenv("MAVEN_TOKEN")
                    }
                }
            }
        } else {
            mavenLocal()
        }
    }
}