package io.github.lounode.eventwrapper.eventbus.api;


import io.github.lounode.eventwrapper.eventbus.EventListenerFactory;

;

/**
 * Base class for event listeners generated by {@link EventListenerFactory}.
 */
public abstract non-sealed class GeneratedEventListener extends EventListener {
}
